problem_types: [assembly]
enhance_highway: false
initial_element_collision: true
self_collisions: false
arm_ik_sample_num: 3
PRM_method: PRM
post_max_duration: 0.1
PRM_edge_max_duration: 1
PRM_vertex_max_degree: 10
PRM_arm_sample_num: 100
RRT_max_duration: 3
RRT_max_iteration: 3000
RRT_max_path_length: 100
connection_max_duration: 3
connection_max_degree: 20
roadmap_joint_resolution: [0.01,0.01,0.01,0.01,0.01,0.01]
annotation_post_max_duration: 0.02